version: "3.3"
services:
  mysql:
    image: mysql:5.7 # MySQLのバージョン
    container_name: db-for-go

    # MySQLの設定値
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    # コンテナ内で使用する環境変数
    environment:
      MYSQL_ROOT_USER: "root" # MySQLのルートユーザ名
      MYSQL_ROOT_PASSWORD: "pass" # MySQLのルートユーザのパスワード
      MYSQL_DATABASE: "sampledb" # MySQLに用意されている初期データベースの名前
      MYSQL_USER: "docker" # MySQLのユーザ名
      MYSQL_PASSWORD: "docker" # MySQLのユーザパスワード
      TZ: "Asia/Tokyo"

    # コンテナの3306番ポートを、ローカルの3306番ポートにつなげる
    ports:
      - "3306:3306"

    # コンテナ内にあるMySQLに格納するデータを永続化させるために使用するボリュームを指定
    volumes:
      - db-volume:/var/lib/mysql

# ボリュームの作成
volumes:
  db-volume:
